alias n='cd /var/log/nginx'
alias gc='git commit -a'
alias gs='git log -p --stat --color'
alias a='more ~/.bash_aliases'
alias cp='/bin/cp -v'
alias mv='/bin/mv -v'
alias rm='/bin/rm -v'
alias ln='/bin/ln -v'
